export const homeObjecOne = {
  id: "about",
  to: "services",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "เกี่ยวกับ",
  headline: "Handmade Jipatha Shop",
  description: "ร้านเราจำหน่ายสินค้า handmade ที่ออกแบบเองทำเองทุกชิ้น มีหลายอย่างให้ท่านได้เลือกซื้ออาทิเช่น สมุดบันทึก, กระปุกออมสิน, พวงกุญแจ และงานถักไหมพรมต่างๆอีกมากหลาย",
  buttonLable: "ถัดไป",
  imgStart: true,
  img: require("../../images/logo.png"),
  alt: "Handmade Jipatha",
  dark: false,
  primary: false,
  darkText: true,
};

// export const homeObjecTwo = {
//   id: "contact",
//   to: "services",
//   lightBg: true,
//   lightText: false,
//   lightTextDesc: false,
//   topLine: "ติดต่อ",
//   headline: "...",
//   description: "...",
//   buttonLable: "Lend More",
//   imgStart: false,
//   img: require("../../images/svg-2.svg"),
//   alt: "svg2",
//   dark: false,
//   primary: false,
//   darkText: true,
// };

// export const homeObjecThree = {
//   id: "signup",
//   lightBg: true,
//   lightText: false,
//   lightTextDesc: false,
//   topLine: "Join out",
//   headline: "....",
//   description: "...",
//   buttonLable: "Start now",
//   imgStart: false,
//   img: require("../../images/svg-3.svg"),
//   alt: "join",
//   dark: false,
//   primary: false,
//   darkText: true,
// };